<?php

/**
 * Implementation of hook_menu().
 */
function xmi_export_menu() {
    $items['xmi-export'] = array(
        'title' => 'Export XMI',
        'page callback' => 'xmi_export_page',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'xmi_export.inc',
    );

    /* XMI */
    $items['xmi.xml'] = array(
        'title' => 'xmi.xml',
        'page callback' => 'xmi_export_xmi',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'xmi_export.inc',
    );
    
    $items['package/%/xmi.xml'] = array(
        'title' => 'xmi.xml',
        'page callback' => 'xmi_export_xmi',
        'access arguments' => array('access content'),
        'page arguments' => array(1),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'xmi_export.inc',
    );
    
    /* Docbook */
    $items['docbook.xml'] = array(
        'title' => 'docbook.xml',
        'page callback' => 'docbook_export',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'docbook_export.inc',
    );
    
    $items['package/%/docbook.xml'] = array(
        'title' => 'docbook.xml',
        'page callback' => 'docbook_export',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'docbook_export.inc',
    );    

    $items['docbook.html'] = array(
        'title' => 'docbook.html',
        'page callback' => 'docbook_html',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'docbook_export.inc',
    );

    /* Graph */
    $items['package/%/dot.txt'] = array(
        'title' => 'DOT dump per package',
        'page callback' => 'dot_package_export',
        'access arguments' => array('access content'),
        'page arguments' => array(1),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'graph.inc',
    );    
    
    $items['objects.json'] = array(
        'title' => 'JSON data for graph (not used)',
        'page callback' => 'graph_json',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'graph.inc',
    );

    $items['objects.dot'] = array(
        'title' => 'docbook.html',
        'page callback' => 'graph_dot',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'graph.inc',
    );    
    
    $items['graph'] = array(
        'title' => 'Graph of all objects',
        'page callback' => 'graph_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'graph.inc',
    );
    
    $items['graph/dot'] = array(
        'title' => 'Graph in dot',
        'page callback' => 'dot_graph_page',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'graph.inc',
    );

    return $items;
}

/**
 * implement hook_theme
 * @return list for avalible themes
 */
function xmi_export_theme() {
    $path = drupal_get_path('module', 'xmi_export') . '/templates';
    return array(
        'xmi' => array(
            'path' => $path,
            'template' => 'xmi',
            'variables' => array('objects' => NULL),
        ), 'xmi_cardinality' => array(
            'path' => $path,
            'template' => 'xmi_cardinality',
            'variables' => array('object' => NULL, 'cardinality' => NULL, 'property' => NULL),
        ), 'docbook' => array(
            'path' => $path,
            'template' => 'docbook',
            'variables' => array('objects' => NULL),
        ),'dot' => array(
            'path' => $path,
            'template' => 'dot',
            'variables' => array('dot' => NULL)
    ));
}