<?php

/**
 * Implementation of hook_menu().
 */
function ddi_model_import_menu() {
    $items['ddi-model-import'] = array(
        'title' => 'Import DDI Model from Excel',
        'page callback' => 'ddi_model_import_page',
        'access arguments' => array('administer modules'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'ddi_model_import.inc',
    );
    return $items;
}

/**
 * implement hook_theme
 * @return list for avalible themes
 */
function ddi_model_import_theme() {
    $path = drupal_get_path('module', 'ddi_model_import') . '/templates';
    return array(
        'import.log' => array(
            'path' => $path,
            'template' => 'import.log',
            'variables' => array('log' => NULL),
        )
    );
}